version: '3'

services:
  # C++ services
  cpp1:
    container_name: cpp1s
    image: lcpolice/cpp:1.2.0
    ports:
      - "8081:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "g++", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  cpp2:
    container_name: cpp2
    image: lcpolice/cpp:1.2.0
    ports:
      - "8082:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "g++", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  cpp3:
    container_name: cpp3
    image: lcpolice/cpp:1.2.0
    ports:
      - "8083:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "g++", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  cpp4:
    container_name: cpp4
    image: lcpolice/cpp:1.2.0
    ports:
      - "8084:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "g++", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  cpp5:
    container_name: cpp5
    image: lcpolice/cpp:1.2.0
    ports:
      - "8085:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "g++", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  cpp6:
    container_name: cpp6
    image: lcpolice/cpp:1.2.0
    ports:
      - "8086:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "g++", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  cpp7:
    container_name: cpp7
    image: lcpolice/cpp:1.2.0
    ports:
      - "8087:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "g++", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  cpp8:
    container_name: cpp8
    image: lcpolice/cpp:1.2.0
    ports:
      - "8088:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "g++", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  cpp9:
    container_name: cpp9
    image: lcpolice/cpp:1.2.0
    ports:
      - "8089:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "g++", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  cpp10:
    container_name: cpp10
    image: lcpolice/cpp:1.2.0
    ports:
      - "8090:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "g++", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  # # JavaScript services
  js1:
    container_name: js1
    image: lcpolice/js:1.2.0
    ports:
      - "8091:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "node", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  js2:
    container_name: js2
    image: lcpolice/js:1.2.0
    ports:
      - "8092:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "node", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  js3:
    container_name: js3
    image: lcpolice/js:1.2.0
    ports:
      - "8093:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "node", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  js4:
    container_name: js4
    image: lcpolice/js:1.2.0
    ports:
      - "8094:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "node", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  js5:
    container_name: js5
    image: lcpolice/js:1.2.0
    ports:
      - "8095:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "node", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  js6:
    container_name: js6
    image: lcpolice/js:1.2.0
    ports:
      - "8096:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "node", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  js7:
    container_name: js7
    image: lcpolice/js:1.2.0
    ports:
      - "8097:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "node", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  js8:
    container_name: js8
    image: lcpolice/js:1.2.0
    ports:
      - "8098:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "node", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  js9:
    container_name: js9
    image: lcpolice/js:1.2.0
    ports:
      - "8099:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "node", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  js10:
    container_name: js10
    image: lcpolice/js:1.2.0
    ports:
      - "8100:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "node", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  # Java services
  java1:
    container_name: java1
    image: lcpolice/java:1.2.0
    ports:
      - "8101:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "java", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  java2:
    container_name: java2
    image: lcpolice/java:1.2.0
    ports:
      - "8102:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "java", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  java3:
    container_name: java3
    image: lcpolice/java:1.2.0
    ports:
      - "8103:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "java", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  java4:
    container_name: java4
    image: lcpolice/java:1.2.0
    ports:
      - "8104:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "java", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  java5:
    container_name: java5
    image: lcpolice/java:1.2.0
    ports:
      - "8105:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "java", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  java6:
    container_name: java6
    image: lcpolice/java:1.2.0
    ports:
      - "8106:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "java", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  java7:
    container_name: java7
    image: lcpolice/java:1.2.0
    ports:
      - "8107:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "java", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  java8:
    container_name: java8
    image: lcpolice/java:1.2.0
    ports:
      - "8108:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "java", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  java9:
    container_name: java9
    image: lcpolice/java:1.2.0
    ports:
      - "8109:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "java", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  java10:
    container_name: java10
    image: lcpolice/java:1.2.0
    ports:
      - "8110:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "java", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  # Python services
  py1:
    container_name: py1
    image: lcpolice/python:1.2.0
    ports:
      - "8111:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "python3", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  py2:
    container_name: py2
    image: lcpolice/python:1.2.0
    ports:
      - "8112:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "python3", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  py3:
    container_name: py3
    image: lcpolice/python:1.2.0
    ports:
      - "8113:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "python3", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  py4:
    container_name: py4
    image: lcpolice/python:1.2.0
    ports:
      - "8114:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "python3", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  py5:
    container_name: py5
    image: lcpolice/python:1.2.0
    ports:
      - "8115:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "python3", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  py6:
    container_name: py6
    image: lcpolice/python:1.2.0
    ports:
      - "8116:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "python3", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  py7:
    container_name: py7
    image: lcpolice/python:1.2.0
    ports:
      - "8117:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "python3", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  py8:
    container_name: py8
    image: lcpolice/python:1.2.0
    ports:
      - "8118:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "python3", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  py9:
    container_name: py9
    image: lcpolice/python:1.2.0
    ports:
      - "8119:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "python3", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3

  py10:
    container_name: py10
    image: lcpolice/python:1.2.0
    ports:
      - "8120:8080"
    networks:
      - mynetwork
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "python3", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3
     
networks: 
  mynetwork: 
    driver: bridge

#to be added  
# healthcheck:
#       test: ["CMD", "g++", "--version"]
#       interval: 30s
#       timeout: 3s
#       retries: 3
#     restart: unless-stopped
