FROM alpine:3.19

# Set the JAVA_HOME environment variable
ENV JAVA_HOME=/usr/lib/jvm/default-jvm

# Install Java (OpenJDK 17)
RUN apk add --no-cache openjdk17 && \
    ln -sf "${JAVA_HOME}/bin/"* "/usr/bin/"

# Install Go
RUN apk add --no-cache go

# Copy the server.go file into the container
COPY server.go server.go

# Command to run the Go server
CMD ["go", "run", "server.go"]
